spring:
    datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver

    jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      open-in-view: false
    jdbc:
      time-zone: UTC

  sql:
    init:
      platform: postgres
      mode: always






#spring:
#  datasource:
#    username:
#    password:
#    url:
#    driver-class-name:
#
#  jpa:
#    dialect: org.hibernate.dialect.postgreSQLDialect
#    jdbc:
#      time-zone: UTC
#    show-sql: false #Set true for debugging
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#      open-in-view: false
#  sql:
#    init:
#      platform: postgres
#      mode: always













#  spring.datasource.url=${JDBC_DATABASE_URL}
#spring.datasource.username=${JDBC_DATABASE_USERNAME}
#spring.datasource.password=${JDBC_DATABASE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true




